### ISSUE TITLE
Running COLMAP on existing images fails to converge

### ISSUE THREAD

**Issue by gchhablani** [TUTvision/MuSHRoom#3]
I tried running colmap on the images in the activity dataset.
COLMAP fails to converge on this. I wonder why should that be the case, assuming there are already the poses based on COLMAP.

**Comment by XuqianRen** [comment]
@gchhablani Hi, the activity room is very complicated, so COLMAP fails on this scene and the "koivu" scene with the iPhone sequence. The poses of these two scenes are from the polycam pose. But to facilitate batch training/testing script, I also name the pose transformation scripts as transformation_colmap.json for easy use.
