### ISSUE TITLE
Question about texture

### ISSUE THREAD

**Issue by BooguTeam** [TUTvision/MuSHRoom#7]
Hi, thanks a lot for the elaborate work. I downloaded the data and observed that there contains two mesh with different textures. (one with the material_0.jpeg, the other is the texture_0_***.jpg)
I am wondering which one is generated using **Texturing an existing mesh with NeRF** and what's the difference between these two textured mesh?

Besides, the size of the texture image is not like a manually set number, like 8192x5504. I am curious whether the texture is generated by https://github.com/TUTvision/MuSHRoom/blob/3f36dbfe24c783f85e320a613096eee5216839eb/mushroom_method/nerfstudio/exporter/texture_utils.py#L369

**Comment by XuqianRen** [comment]
Hi @Harr7y I didn't release the mesh generated from the texture_utils.py, the mesh I released under the iphone folder "polycam_folder" with texture_0_***.jpg and  "material_0.jpeg" is a mesh exported from polycam app, they are generated by polycam this app, it is just for visualization, the mesh is centered and didn't align with the poses I provided under the transformation_colmap.json (the pose calculated from colmap) / transformation.json (the pose provided by polycam). You don't need to use the mesh under this "polycam_folder" folder. 

For the geometry comparison, you can use the gt_mesh.ply under this link https://zenodo.org/records/10222321. The mesh is get from faro scanner point cloud, and we provide the transformation matrix to align the mesh with the kinect/iphone colmap pose.

**Comment by Harr7y** [comment]
Thanks a lot for your reply~
